"use client";

import jsPDF from "jspdf";

export type SalarySlipPayload = {
  instituteName: string;
  staffName: string;
  employeeId: string;
  month: string;
  staffType: "teacher" | "senior_teacher";
  monthlySalary: number;
  weekdayBatches: number;
  weekendBatches: number;
  totalBatches: number;
  salaryPerBatch: number;
  presentCount: number;
  absentCount: number;
  halfDayCount: number;
  leaveCount: number;
  rejectedLeaveCount: number;
  pendingLeaveCount: number;
  deductionAmount: number;
  netSalary: number;
  payrollStatus: string;
};

function money(value: number): string {
  return `INR ${value.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
}

function drawSalarySlipPage(doc: jsPDF, payload: SalarySlipPayload) {
  doc.setFontSize(16);
  doc.text(payload.instituteName, 14, 18);
  doc.setFontSize(11);
  doc.text("Salary Slip", 14, 26);
  doc.text(`Month: ${payload.month}`, 150, 26);

  doc.setFontSize(10);
  doc.text(`Teacher Name: ${payload.staffName}`, 14, 38);
  doc.text(`Employee ID: ${payload.employeeId}`, 14, 45);
  doc.text(`Role: ${payload.staffType === "teacher" ? "Teacher" : "Senior Teacher"}`, 14, 52);
  doc.text(`Status: ${payload.payrollStatus}`, 14, 59);

  doc.setFontSize(11);
  doc.text("Attendance Summary", 14, 74);
  doc.setFontSize(10);
  doc.text(`Present: ${payload.presentCount}`, 14, 82);
  doc.text(`Absent: ${payload.absentCount}`, 14, 89);
  doc.text(`Half Day: ${payload.halfDayCount}`, 14, 96);
  doc.text(`Approved Leave: ${payload.leaveCount}`, 14, 103);
  doc.text(`Rejected Leave: ${payload.rejectedLeaveCount}`, 14, 110);
  doc.text(`Pending Leave: ${payload.pendingLeaveCount}`, 14, 117);

  doc.setFontSize(11);
  doc.text("Batch Summary", 110, 74);
  doc.setFontSize(10);
  doc.text(`Weekday Batches: ${payload.weekdayBatches}`, 110, 82);
  doc.text(`Weekend Batches: ${payload.weekendBatches}`, 110, 89);
  doc.text(`Total Batches: ${payload.totalBatches}`, 110, 96);
  doc.text(`Salary / Batch: ${money(payload.salaryPerBatch)}`, 110, 103);

  doc.setFontSize(11);
  doc.text("Salary Details", 14, 132);
  doc.setFontSize(10);
  doc.text(`Monthly Salary: ${money(payload.monthlySalary)}`, 14, 140);
  doc.text(`Total Deduction: ${money(payload.deductionAmount)}`, 14, 147);
  doc.setFontSize(12);
  doc.text(`Net Salary: ${money(payload.netSalary)}`, 14, 156);

  doc.setFontSize(8);
  doc.text("Generated by SP Art Hub ERP", 14, 285);
}

export function downloadSalarySlipPdf(payload: SalarySlipPayload) {
  const doc = new jsPDF();
  drawSalarySlipPage(doc, payload);

  const safeMonth = payload.month.replace(/[^0-9-]/g, "");
  const safeName = payload.staffName.replace(/\s+/g, "_");
  doc.save(`salary-slip-${safeName}-${safeMonth}.pdf`);
}

export function downloadAllSalarySlipsPdf(
  entries: Omit<SalarySlipPayload, "instituteName">[],
  instituteName: string,
  month: string,
) {
  if (entries.length === 0) return;

  const doc = new jsPDF();
  entries.forEach((entry, index) => {
    if (index > 0) doc.addPage();
    drawSalarySlipPage(doc, { instituteName, ...entry });
  });

  const safeMonth = month.replace(/[^0-9-]/g, "");
  doc.save(`salary-slips-all-${safeMonth}.pdf`);
}
